<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeXrSEx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeXrSEx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUeXrSEx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUeXrSEx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUeXrSEx\App_KernelDevDebugContainer([
    'container.build_hash' => 'UeXrSEx',
    'container.build_id' => '11a3e472',
    'container.build_time' => 1696575078,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUeXrSEx');
