<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH2PKt7a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH2PKt7a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH2PKt7a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH2PKt7a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH2PKt7a\App_KernelDevDebugContainer([
    'container.build_hash' => 'H2PKt7a',
    'container.build_id' => 'c1831b02',
    'container.build_time' => 1696576796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH2PKt7a');
